/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRulesRouteImport } from './routes/_app/rules'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppCardsRouteImport } from './routes/_app/cards'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppFactionsRouteRouteImport } from './routes/_app/factions/route'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFactionsRouteRoute = AppFactionsRouteRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/factions': typeof AppFactionsRouteRoute
  '/about': typeof AppAboutRoute
  '/cards': typeof AppCardsRoute
  '/contact': typeof AppContactRoute
  '/rules': typeof AppRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/factions': typeof AppFactionsRouteRoute
  '/about': typeof AppAboutRoute
  '/cards': typeof AppCardsRoute
  '/contact': typeof AppContactRoute
  '/rules': typeof AppRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/factions': typeof AppFactionsRouteRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/cards': typeof AppCardsRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/rules': typeof AppRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/factions' | '/about' | '/cards' | '/contact' | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/factions' | '/about' | '/cards' | '/contact' | '/rules'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/factions'
    | '/_app/about'
    | '/_app/cards'
    | '/_app/contact'
    | '/_app/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/factions': {
      id: '/_app/factions'
      path: '/factions'
      fullPath: '/factions'
      preLoaderRoute: typeof AppFactionsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppFactionsRouteRoute: typeof AppFactionsRouteRoute
  AppAboutRoute: typeof AppAboutRoute
  AppCardsRoute: typeof AppCardsRoute
  AppContactRoute: typeof AppContactRoute
  AppRulesRoute: typeof AppRulesRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppFactionsRouteRoute: AppFactionsRouteRoute,
  AppAboutRoute: AppAboutRoute,
  AppCardsRoute: AppCardsRoute,
  AppContactRoute: AppContactRoute,
  AppRulesRoute: AppRulesRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
