#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Pre-commit hook"

# Load nvm if available
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
  nvm use --silent
fi

npm test
npx lint-staged
